name: Tenants generator

on:
  workflow_dispatch:
    inputs:
      database:
        description: 'Select the database environment'
        required: true
        type: choice
        options:
          - DDAI_DW_NONPRD
          - DDAI_DW_PRD
      branch:
        description: 'Branch to run the workflow from'
        required: true
        type: choice
        options:
          - master
          - qat
        default: qat

jobs:
  generate_and_commit:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          ref: ${{ inputs.branch }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.4'

      - name: Install dependencies
        run: pip install -r .github/workflows/src/requirements.txt

      - name: Run Python script
        run: python .github/workflows/src/customer_models_generator.py
        env:
          # Pass PostgreSQL credentials as environment variables
          POSTGRES_HOST: ${{ secrets.POSTGRES_HOST }}
          POSTGRES_PORT: ${{ secrets.POSTGRES_PORT }}
          POSTGRES_DATABASE: ${{ inputs.database }}
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}

      - name: Configure Git
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

      - name: Commit changes
        run: |
          git checkout -b multi_tenant_generation
          git add ../models/customers/
          git commit -m "Add generated SQL files"
        working-directory: models

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: multi_tenant_generation